index_dir = "Wiki_index"
xml_file = "xml_snippet"

# Test samples
# relevant_pages = {"Anarchism", "Autism", "AccessibleComputing", "AfghanistanGeography", "AfghanistanPeople"}
# relevant_pages = {"Autism"}

# Actual set
# ----Search settings
# results per page: 40
# region settings: United Kingdom
# Google language: English
# site filter: en.wikipedia.org

relevant_pages = {
    'Power of a test',
    'Crisis of the Third Century',
    'Mars sample-return mission',
    'List of Nobel laureates affiliated with the University of Edinburgh',
    'McIntyre System',
    'Wadjet',
    'Closure (computer programming)',
    'Signing of the United States Constitution',
    'Microsoft Office 2019',
    'List of American films of 2020',
    'Palindrome',
    '2010%E2%80%932014 Portuguese financial crisis',
    'Photovoltaic system',
    'Nemesis',
    'Precision (statistics)',
    'Serekh',
    'Maya calendar',
    'List of birds of Egypt',
    'Ania Marson',
    'Pearson%27s chi-squared test',
    'Yalalag cross',
    'List of Roman emperors',
    'State church of the Roman Empire',
    'Solarflesh %E2%80%93 A Gospel of Radiant Divinity',
    'Sustainable energy',
    'Grace Hopper',
    'ATHLETE',
    'Tuscany',
    'Nobel Prize',
    'Daniel Lapin',
    'Talk%3AHawkshaw Bridge',
    'Call Me Madam (film)',
    'Eddie Chapman',
    'Solar power in Portugal',
    'Gauss%E2%80%93Newton algorithm',
    'Outline of computer programming',
    'Pekka Airaksinen',
    'Category:Computer programming',
    'Size (statistics)',
    'Talk%3AClever Hans',
    'What Goes Around... Comes Around',
    'Fourteenth Amendment to the United States Constitution',
    'List of countries by apple production',
    'Java (programming language)',
    'Solar power in Greece',
    'Total least squares',
    'Justin Timberlake videography',
    'Template:Ifnumber',
    'Null hypothesis',
    'Linear least squares',
    'C (programming language)',
    'CEEQUAL',
    'Palenque',
    'Article Four of the United States Constitution',
    'Epigenetic theories of homosexuality',
    'Wikipedia:Manual of Style',
    'File:Eye of Horus bw.svg',
    'Evaluation of binary classifiers',
    'Triple Crossed',
    'Wayne Darwen',
    'Solar power',
    'Numerical methods for linear least squares',
    'Space-based solar power',
    'Roman Syria',
    'President of Tuscany',
    'Se%C3%B1orita (Justin Timberlake song)',
    'Mars Helicopter Ingenuity',
    'Article Five of the United States Constitution',
    'NSYNC',
    'Goldfinger discography',
    'James Brady (columnist)',
    'Hapi (Son of Horus)',
    'Category:People from Tuscany',
    'Solar cell',
    'C. H. Waddington',
    'SixDegrees.com',
    'Angry Salad (album)',
    'Swedish banking rescue',
    'Nobel Prize controversies',
    'Deborah Jeane Palfrey',
    'Solar power in the United States',
    'Reflection (computer programming)',
    'Stephanie Trong',
    'Uraeus',
    'Disney%27s Hollywood Studios',
    'Metternich Stela',
    'The Snow Goose: A Story of Dunkirk',
    'Pharmacoepigenetics',
    'DNA profiling',
    'Steve Jobs',
    'Learning to rank',
    'Guest of a Guest',
    'Lift (data mining)',
    'Madam Secretary (TV series)',
    'Windows 1.0',
    'The Justified World Tour',
    'Red Balloon',
    'Cabinet Manual',
    'James Frey',
    'Some Nights (song)',
    'Talk%3AJustin Timberlake%2FArchive 1',
    'The Second Coming of Steve Jobs',
    'List of artistic depictions of Steve Jobs',
    'Programming paradigm',
    'Blair Underwood',
    'Ancient Maya graffiti',
    'DNA vaccination',
    'Maya Ballgame',
    'Confidence interval',
    'Ancient Rome',
    'Linear regression',
    'Apple Store',
    'Second Spanish Republic',
    'Template:Exorcists Manual',
    'Great Recession',
    'Solar Energy Perspectives',
    'Chromatin',
    'Psychology of programming',
    'Peafowl',
    'Query expansion',
    '99',
    'List of Microsoft Office programs',
    'History of Microsoft',
    'Microsoft 365',
    'Encapsulation (computer programming)',
    'Republican faction (Spanish Civil War)',
    'Young and Rich',
    'Tuscan',
    'Explained sum of squares',
    'A%27Lelia Walker',
    'List of Nobel laureates by country',
    'Precision (march)',
    'Talk%3ASteve Jobs',
    'Statistics',
    'List of prizes known as the Nobel of a field or the highest honors of a field',
    'Panic of 1893',
    'Maya codices',
    'List of countries by Nobel laureates per capita',
    'IWork',
    'Jessica Biel',
    'Nena',
    'Maya astronomy',
    'Precision',
    'Normal distribution',
    'Mars Pathfinder',
    'Constrained least squares',
    'Battle of Belchite (1937)',
    'Eye of Providence',
    'Viking 1',
    'Epigenome editing',
    'Owner%27s manual',
    'Nucleic acid structure',
    'Standard deviation',
    'Epigenetics of autism',
    'Resampling (statistics)',
    'Forest Lawn Memorial Park (Hollywood Hills)',
    'Exploration of Mars',
    'Global financial crisis in 2009',
    'Epigenetics in learning and memory',
    'Subprime mortgage crisis',
    'Major film studio',
    'Solar thermal energy',
    'Eye of Horus',
    'Xibalba',
    'Epigenetic (disambiguation)',
    'List of Ig Nobel Prize winners',
    'Ferdinando I de%27 Medici, Grand Duke of Tuscany',
    'Criticism of Apple Inc.',
    'Evacuation of children in the Spanish Civil War',
    'Gate deities of the underworld',
    'Operator (computer programming)',
    'Volcano plot (statistics)',
    'Geohash',
    'Apple Inc. design motifs',
    'Hathor',
    'Loss of significance',
    'Wikipedia:WikiProject Justin Timberlake',
    'Template talk:US Constitution article series',
    'Hemen',
    'Lack-of-fit sum of squares',
    'Map (disambiguation)',
    'F1 score',
    'Triplecross lizardfish',
    'Hitechjet',
    'Spanish coup of July 1936',
    'The Twenty-One Balloons',
    'Moving least squares',
    'Programmer',
    'Panic of 1857',
    'Paired difference test',
    'DNA',
    'Man page',
    'Holy Roman Empire',
    'RNA polymerase',
    'Computer code',
    'List of rulers of Tuscany',
    'Comparison of embedded computer systems on board the Mars rovers',
    'M.I.A. (rapper)',
    'List of Nobel laureates',
    'Statistical significance',
    'Timeline of Steve Jobs media',
    'Girl with Balloon',
    'Precision teaching',
    'Simple linear regression',
    'Hollywood Bowl',
    'Epigenetics (journal)',
    'Tear Ceremony',
    'History of Apple Inc.',
    'History of Rome',
    'March of Tuscany',
    'Behavioral epigenetics',
    'List of mergers and acquisitions by Apple',
    'Category:Wikipedia Manual of Style (music)',
    'Maya warfare',
    'Mean absolute error',
    'List of Hollywood-inspired nicknames',
    'Maya households',
    'Relevance feedback',
    'Student%27s t-test',
    'Solar power in Denmark',
    'Nobel Committee for Physics',
    'Xbox Game Studios',
    'Weighted least squares',
    'Epigenetics of schizophrenia',
    'DNA barcoding',
    'Mesopotamia (Roman province)',
    'New Hollywood',
    'Hollywood (miniseries)',
    'List of black Nobel laureates',
    'P-value',
    'Russian Orthodox cross',
    'Category:Roman sites of Tuscany',
    'Six degrees of separation',
    'Windows Vista',
    'Grand Duchy of Tuscany',
    'Deviation (statistics)',
    'Precision (computer science)',
    'Precision bombing',
    'Criticism of Microsoft',
    'Apple Inc.',
    'Book:Epigenetics',
    'Scotty and the Secret History of Hollywood',
    'Complementary DNA',
    'Good Omens (TV series)',
    'Outline of Apple Inc.',
    'Fall of the Western Roman Empire',
    'Bennu',
    'Panic of 1825',
    'Wall Street and the Financial Crisis: Anatomy of a Financial Collapse',
    'Category:Albums produced by Justin Timberlake',
    'Mars Piloted Orbital Station',
    'Microsoft Publisher',
    'Inverse-variance weighting',
    'Category:Nobel laureates in Physics',
    'Martin of Tours',
    'Litany of the Eye of Horus',
    'The Red Balloon',
    '2020 Tuscan regional election',
    'Historiography of the fall of the Western Roman Empire',
    'Mayanism',
    'Microsoft Surface',
    '2020 stock market crash',
    'Mars Exploration Program',
    'Greek government-debt crisis',
    'Scotty Bowers',
    'List of artworks known in English by a foreign title',
    'John Bardeen',
    'Solar power in France',
    'Ra',
    'Anarchism in Spain',
    'Talk%3AAccuracy and precision',
    'Epigenetics',
    'Global financial crisis in September 2008',
    'Apple I',
    'DARPA Network Challenge',
    'Talk%3APrecision and recall',
    'New York Post',
    'Catalonia Offensive',
    'Manual for Streets',
    'DNA computing',
    'Precision marketing',
    'Office 365',
    'Coefficient of determination',
    'Round-off error',
    'Category:Precision sports',
    'Holy Spirit in Christianity',
    'Robust regression',
    'SoulMate (Justin Timberlake song)',
    'Leda and the Swan',
    'Wiktionary:Hollywood',
    'Article One of the United States Constitution',
    'Apple Music',
    'Nobel Prize in Chemistry',
    'Tuscan dialect',
    'Maya cuisine',
    'List of solar thermal power stations',
    'Maya (religion)',
    'DNA methylation',
    'DNA (disambiguation)',
    'List of mergers and acquisitions by Microsoft',
    'False precision',
    'Claudia Cohen',
    'List of Maya gods and supernatural beings',
    'Apple Pay',
    'DNA sequencing',
    'Source code',
    'Justin Timberlake',
    'Can%27t Stop the Feeling!',
    'Sojourner (rover)',
    'IPhone X',
    'Category:Justin Timberlake',
    'Laurene Powell Jobs',
    'Credit rating agencies and the subprime crisis',
    'Montecarlo, Tuscany',
    'Horus',
    'Epigenetics of human development',
    '99 Luftballons (album)',
    'Gods of Egypt (film)',
    'File talk:Wedjat (Udjat) Eye of Horus pendant.jpg',
    'List of awards and nominations received by Justin Timberlake',
    'Class (computer programming)',
    'United States Bill of Rights',
    'Eighth Amendment to the United States Constitution',
    'Anubis',
    'West Hollywood, California',
    'IPhone 4S',
    'List of Nobel laureates affiliated with Princeton University',
    'Evaluation measures (information retrieval)',
    'Hollywood blacklist',
    'Category:Tourist attractions in Tuscany',
    'Constitution of the United States',
    'List of tanks in the Spanish Civil War',
    'Artificial precision',
    'Eleventh Amendment to the United States Constitution',
    'Internal Revenue Manual',
    'Category:Song recordings produced by Justin Timberlake',
    'Riviera Maya',
    'Mark Saltveit',
    'Until the End of Time (Justin Timberlake and Beyonc%C3%A9 song)',
    'Z-DNA',
    'Irish involvement in the Spanish Civil War',
    'Bastet',
    'Paula Froelich',
    'Olivia Palermo',
    'Mirrors (Justin Timberlake song)',
    'Timeline of Microsoft',
    'Greylag goose',
    'Talk%3AGran Turismo 3%3A A-Spec',
    'Microsoft OneNote',
    'Michael Mailer',
    'Precision and recall',
    'Wikipedia:Six degrees of Wikipedia',
    'Article Three of the United States Constitution',
    'Feuer und Flamme',
    'Computer programming',
    'List of Nobel laureates in Chemistry',
    'Scouting for Boys',
    'List of states in the Holy Roman Empire',
    'Thirteenth Amendment to the United States Constitution',
    'Chloroplast DNA',
    'Apple (symbolism)',
    'Monteriggioni',
    'Hollywood, Florida',
    'Third Rome',
    'Effects of the Great Recession',
    'Cry Me a River (Justin Timberlake song)',
    'Roman economy',
    'List of banking crises',
    'Timeline of Mars Science Laboratory',
    'Oslo Manual',
    'List of people of the Spanish Civil War',
    'Category:Epigenetics',
    'Jared Paul Stern',
    'Summer Love (Justin Timberlake song)',
    'Mark T. Sullivan',
    'What Do You Want from Live',
    'Manual fire alarm activation',
    'Growth of photovoltaics',
    'Instrumental variables estimation',
    'Category:Justin Timberlake songs',
    'Human mission to Mars',
    'Hollywood Walk of Fame',
    'Steve Jobs (disambiguation)',
    'Nonlinear regression',
    'List of Nobel laureates by university affiliation',
    'Shapiro%E2%80%93Wilk test',
    'Christopher Plummer',
    'Exact test',
    'Lisa Brennan-Jobs',
    'Precision bias',
    'Tuscany (disambiguation)',
    'Symmetric mean absolute percentage error',
    'Iteratively reweighted least squares',
    'Solar energy',
    'Preamble to the United States Constitution',
    'Swan',
    'No gods, no masters',
    'Microsoft Live',
    'One- and two-tailed tests',
    'Mean squared error',
    'Mars landing',
    'Operations manual',
    'Topics',
    'Wikipedia:Simplified Manual of Style',
    'Dear Maya',
    'United States v. Microsoft Corp.',
    'List of clauses of the United States Constitution',
    'Q-value (statistics)',
    'Sample size determination',
    'The Independent %282000 film%29',
    'J.W. Hodkinson',
    'Justin Timberlake discography',
    'Template:Least squares and regression analysis',
    'Category:Battles of the Spanish Civil War',
    'Nucleic acid double helix',
    'Nobel Peace Prize',
    'Article Six of the United States Constitution',
    'Sensitivity and specificity',
    'Borders of the Roman Empire',
    'Solar panel',
    'Renewable energy',
    'Stock market crash',
    'NeXT',
    'Holy Roman Emperor',
    'Microsoft Notepad',
    'Constitution of the Roman Empire',
    'Chinese goose',
    'Epigenomics',
    'History of Tuscany',
    'Human%E2%80%93computer information retrieval',
    'Maya Herrera',
    'Mitochondrial DNA',
    'List of Roman dynasties',
    'Final offensive of the Spanish Civil War',
    'Tuscan wine',
    'Classic Maya collapse',
    'Constitution',
    'Adam Ant',
    'Man of the Woods',
    'Epigenetic regulation of neurogenesis',
    'Mars program',
    'Farmers Manual',
    'Tikhonov regularization',
    'Category:Cancer epigenetics',
    'Maya religion',
    'Accessibility',
    'List of Japanese Nobel laureates',
    'Windows XP',
    '2007 May 29',
    'Twelfth Amendment to the United States Constitution',
    'Type I and type II errors',
    'Tianwen-1',
    'Misuse of p-values',
    'Maya rulers',
    'ICloud',
    'Contribution of epigenetic modifications to evolution',
    'Recursive least squares filter',
    'Six Finger Satellite',
    'Talk%3A99 Luftballons',
    'Article Seven of the United States Constitution',
    'Bonferroni correction',
    'Epigenetics of plant growth and development',
    'AFI%27s 100 Years...100 Stars',
    'Maya (1966 film)',
    'Geb',
    'Hollywood Forever Cemetery',
    'Category:Government of the Roman Empire',
    'Like I Love You',
    'Statistical dispersion',
    'Adam Levine',
    'Government policies and the subprime mortgage crisis',
    'Talk%3ARTFM',
    'Epigenetics of depression',
    'Patina Miller',
    'List of missions to Mars',
    'Object-oriented programming',
    'Maya stelae',
    'Least-squares function approximation',
    'Roman Britain',
    'Trivia sections',
    'Opportunity (rover)',
    'File:COAppiusix.png',
    'G-test',
    'Non-coding DNA',
    'Maya architecture',
    'Bombing of Guernica',
    'Human Y-chromosome DNA haplogroup',
    'Windows 8',
    'Panic of 1873',
    'List of consorts of Tuscany',
    'Mandy Stadtmiller',
    'Rock Your Body',
    'Template talk:Nobel Prize in Physics',
    'Becoming Steve Jobs',
    'Classical Hollywood cinema',
    'List of Nobel laureates affiliated with King%27s College London',
    'Category:Battles in Tuscany',
    'Chrisann Brennan',
    'Maya peoples',
    'Spanish Civil War',
    'List of Apple Inc. media events',
    'Category:Microsoft acquisitions',
    'Partial least squares regression',
    'Genome',
    'Fifteenth Amendment to the United States Constitution',
    'Statistical hypothesis testing',
    'Maya (given name)',
    'List of surviving veterans of the Spanish Civil War',
    'Information retrieval',
    'Triple Cross',
    'Regional Council of Tuscany',
    'Motion Picture Production Code',
    'Hollywood (British TV series)',
    'Arbitrary-precision arithmetic',
    'Concentrated solar power',
    'q:Steve Jobs',
    'COSC',
    'DNA mismatch repair',
    'Solar panels on spacecraft',
    'Thoth',
    'List of playing-card nicknames',
    'Madam Adam',
    'Stephen Tobolowsky',
    'Nena (album)',
    'Tunnel Vision (Justin Timberlake song)',
    'Category:Cities and towns in Tuscany',
    'Hollywood (2002 film)',
    'Universal Studios Hollywood',
    'Aphrodite',
    'Keith Carradine',
    'History of the United States Constitution',
    'DNA virus',
    'Where Is the Love%3F',
    'Lamarckism',
    'Osiris',
    'Christmas Is Coming',
    'Spanish Revolution of 1936',
    'Under the Tuscan Sun (film)',
    'Iron Guard',
    'Twentieth Amendment to the United States Constitution',
    'University Rover Challenge',
    'Epigenetics in forensic science',
    'Foreign involvement in the Spanish Civil War',
    'Epigenetic code',
    'Alternative text for images',
    'Cabaret (Justin Timberlake song)',
    'DNA polymerase',
    'Algorithms for calculating variance',
    'Women on the Nationalist side of the Spanish Civil War',
    'Mars 2020',
    'Triple product',
    'ICon: Steve Jobs',
    'Simultaneous equations model',
    'Microsoft Store',
    'Ordinary least squares',
    'Regulatory responses to the subprime crisis',
    'Steve Jobs: The Man in the Machine',
    'Triquetra',
    'List of female Nobel laureates',
    'Apple',
    '99 Luftballons',
    'Mars (mythology)',
    'Maya script',
    'List of Maya sites',
    'Wikipedia:Wiki Game',
    'InSight',
    'Minsky moment',
    'Reality distortion field',
    'Maya',
    'Sir',
    'Chromosome',
    'Mean absolute scaled error',
    'Category:Accuracy and precision',
    'Owner%27s Manual (TV series)',
    'Perseverance (rover)',
    'Fifth Amendment to the United States Constitution',
    'Second Amendment to the United States Constitution',
    'Category:Computer programming tools',
    'One to One (Apple)',
    'Sarah Polonsky',
    'Lead section',
    'Jewish volunteers in the Spanish Civil War',
    'Tenth Amendment to the United States Constitution',
    'Maya (mother of the Buddha)',
    'Music of Tuscany',
    'Rocker-bogie',
    'Category:Roman Empire',
    'Adam Sandler',
    'Least mean squares filter',
    'Mars aircraft',
    'Layshaft',
    'List of Nobel laureates affiliated with University College London',
    'Juno (mythology)',
    'List of Hungarian Nobel laureates',
    'Steve Jobs (clothing company)',
    'Cross of Salem',
    'Tim Cook',
    'Category:Spanish Civil War',
    'Interplanetary contamination',
    'Goose',
    'Photovoltaic power station',
    'Sleepers of Mars',
    'Mars rover',
    'Talk%3APalindrome',
    'Precision rectifier',
    'Microsoft',
    'Steve Jobs (book)',
    'Nationalist faction (Spanish Civil War)',
    'United States Constitution and worldwide influence',
    'Microsoft Store (digital)',
    'Epigenetic clock',
    'List of Nobel laureates affiliated with the University of Cambridge',
    'Category:Provinces of Tuscany',
    'Category:Railway lines in Tuscany',
    'Epigenetics in stem-cell differentiation',
    'Microsoft Word',
    'BASIC',
    'Financial Crisis Inquiry Commission',
    'Microsoft Teams',
    'Holywood',
    'Politics of Tuscany',
    'Souls of Pe and Nekhen',
    '1.96',
    'List of Welsh Nobel laureates',
    'Economic collapse',
    'Peter Frampton',
    'Legacy of the Roman Empire',
    'Crosses in heraldry',
    'Xbox One',
    'Childhood in Maya society',
    'Thomas Schnauz',
    'Category:Nena (band) songs',
    'Training manual',
    'Non-linear least squares',
    'Macintosh',
    'Solar energy in Finland',
    'User guide',
    '20 Experience %E2%80%93 2 of 2',
    'Vinci, Tuscany',
    'Dance Dance Revolution Hottest Party',
    'Photovoltaics',
    'Comment (computer programming)',
    'Epigenetics of physical exercise',
    'Timeline of Apple Inc. products',
    'Timothy McDarrah',
    'Timeline of drafting and ratification of the United States Constitution',
    'Category:Least squares',
    'Tuscan Archipelago',
    'Solar power in Germany',
    'Least squares inference in phylogeny',
    'Elixir (Duff novel)',
    'Solar power by country',
    'List of Nobel laureates affiliated with Imperial College London',
    'Roman province',
    'Nena feat. Nena',
    'Microsoft Bob',
    'Byzantine Empire',
    'Hamsa (bird)',
    'IPhone 4',
    'Beardmore Precision Motorcycles',
    'Bland%E2%80%93Altman plot',
    '1936 in the Spanish Civil War',
    'Epigenetics of neurodegenerative diseases',
    'Solar power in Israel',
    'Demography of the Roman Empire',
    'Sekhmet',
    'Computing',
    'Triple Crossing',
    'Multiple comparisons problem',
    'Talk%3AHit Man manual',
    'Campaign history of the Roman military',
    'File:HorusEye.png',
    'Two six heave',
    'Francoist Spain',
    'Debbie Lee Carrington',
    'Ronald Wayne',
    'Paramount Pictures',
    'Microsoft engineering groups',
    'Women in the Spanish Civil War',
    'Funnel plot',
    'Andrew Huang (musician)',
    'Hollywood',
    'Transfer DNA',
    'Joe Palooka in Triple Cross',
    'Stopwatch',
    'List of Jewish Nobel laureates',
    'Hollywood Sign',
    'Adam and Steve',
    'Once Upon a Time in Hollywood',
    'Mayan languages',
    'Roman emperor',
    'Jobs (film)',
    'Wald test',
    'List of Spanish Civil War films',
    'Papal cross',
    'Women%27s Six Nations Championship',
    'Sacrifice',
    'Aten',
    'A Manual Dexterity: Soundtrack Volume One',
    'Rabbit%E2%80%93duck illusion',
    'Epigenetics of anxiety and stress-related disorders',
    'DNA origami',
    'Anna May Wong',
    'Francis Crick',
    'History of the Roman Empire',
    'Chi-squared test',
    'Weighted arithmetic mean',
    'List of Nobel laureates by secondary school affiliation',
    'Coding',
    'Mayor of Hollywood',
    'Talk%3ASteve Jobs%2FArchive 2',
    'List of Justin Timberlake live performances',
    'Crisis of 1772',
    'Category:Bishops in Tuscany',
    'Spanish conquest of the Maya',
    'The Wind (band)',
    'Non-intervention in the Spanish Civil War',
    'Global economic crisis',
    'Nineteenth Amendment to the United States Constitution',
    'Gib Gas %E2%80%93 Ich will Spass',
    'High-level programming language',
    'Category:Organisations of the Spanish Civil War',
    'Total sum of squares',
    'Positive and negative predictive values',
    'Pixar',
    'Proofs involving ordinary least squares',
    'Recombinant DNA',
    'Gauss%E2%80%93Markov theorem',
    'Sixth Amendment to the United States Constitution',
    'Mesoamerican pyramids',
    'Precision tests of QED',
    'LoveSounds',
    'Genome-wide significance',
    'Goldfinger (band)',
    'Solar power in the United Kingdom',
    'Eighteenth Amendment to the United States Constitution',
    'Georges Garvarentz',
    'Yucatec Maya language',
    'List of amendments to the United States Constitution',
    'The Lone Gunmen (TV series)',
    'ITunes',
    'Lazy Jones',
    'Vero Precision Engineering Ltd',
    'B testing',
    'Hollywood accounting',
    'IPad',
    'Tengri',
    'High-altitude balloon',
    'RTFM',
    'Spirit (rover)',
    'Precision medicine',
    'Maya numerals',
    'Eye of Horus (video game)',
    'Maritime trade in the Maya civilization',
    'Sean Delonas',
    'Siri',
    'Transgenerational epigenetic inheritance',
    'Outline of solar energy',
    'I Know Why the Caged Bird Sings',
    'Timeline of Roman history',
    'Precision glass moulding',
    'NASA robots',
    'App Store (iOS)',
    'Programming language',
    'Category:Tuscany',
    'Windows 7',
    'Frankly, my dear, I don%27t give a damn',
    'Multimode manual transmission',
    'Apple-designed processors',
    'Margin of error',
    'Kelly Killoren Bensimon',
    'List of Indian Nobel laureates',
    '14th Yokohama Film Festival',
    'Regularized least squares',
    'Microsoft Corp. v. Commission',
    'Ig Nobel Prize',
    'Dilution of precision (navigation)',
    'Haplogroup R1b',
    'Estimation statistics',
    'Psychodynamic Diagnostic Manual',
    'Apocalypto',
    'Gert Fr%C3%B6be',
    'List of Belgian Nobel laureates',
    'Apple electric car project',
    'Maya Rudolph',
    'Red Terror (Spain)',
    'Eye of Ra',
    'Category:Wikipedia Manual of Style (content)',
    'Mars Exploration Rover',
    'Microsoft HoloLens',
    'J%C3%B6rn-Uwe Fahrenkrog-Petersen',
    'Mean reciprocal rank',
    'Roman Empire',
    'Template talk:Clist compulsory purchase',
    'Computer program',
    'Triple Cross (1966 film)',
    'Switzerland in the Roman era',
    'Steve Wozniak',
    'Curiosity (rover)',
    'Talk%3AAnagram',
    'List of shows produced by the Endemol Shine Group',
    'My Love (Justin Timberlake song)',
    'Neuroepigenetics',
    'Template:Precision',
    'Microsoft Docs',
    'The Other Side (SZA and Justin Timberlake song)',
    'Causes of the Great Recession',
    'Pisa',
    'Steve Jobs (film)',
    '2012 phenomenon',
    'ISteve',
    'Cross of Lorraine',
    'Egyptian fraction',
    'Numbers in Egyptian mythology',
    'Phoenix (spacecraft)',
    'Background of the Spanish Civil War',
    'Clinical significance',
    'Nena (band)',
    'Matthew 5:8',
    'Wikipedia:How many legs does a horse have%3F',
    'Solar power in Australia',
    'List of Nobel laureates in Physics',
    'Fisher%27s exact test',
    'Roman Empire (disambiguation)',
    'List of Microsoft software',
    'Coefficient of variation',
    'Category:NA-importance The X-Files articles',
    'Windows 10',
    'Keiko Oginome',
    'Solar power in Romania',
    'Financialization',
    'Hollywood and Vine',
    'Computer language',
    'Hollywood, Worcestershire',
    'Talk%3AOrdinary least squares',
    'Treble Cross',
    'The Merck Manuals',
    'Quickstart guide',
    'Mayan Revival architecture',
    'Ninth Amendment to the United States Constitution',
    'Generalized least squares',
    'List of songs about the Cold War',
    '%22Hello, World!%22 program',
    'Isis',
    'Analysis of variance',
    'Made in Germany (Nena album)',
    'List of Apple codenames',
    'Maya Hero Twins',
    'Financial crisis',
    'Microsoft Office',
    'Supplicia canum',
    'Zenia Mucha',
    '?title=Mean average precision&redirect=no',
    'IOS',
    'Computational epigenetics',
    'Florence',
    'Joanna Hoffman',
    'Significance',
    'Template:Spanish Civil War',
    'Category:Balloons (entertainment)',
    'Double Cross',
    'Solar power in Belgium',
    'Solar energy in the European Union',
    'Genealogical DNA test',
    'History of the Maya civilization',
    'DailyFill',
    'wiktionary:Apple',
    'DNA damage (naturally occurring)',
    'Binomial test',
    'Maya city',
    'White Terror (Spain)',
    'Fuzzy retrieval',
    'File:Constitution of the United States, page 1.jpg',
    'Apple III',
    'Women in Maya society',
    'Significant figures',
    'IPod',
    'The Palindromist',
    'Roger Wood (journalist)',
    'Panic of 1907',
    'Genetic testing',
    'Triple Crossed (film)',
    'Portal:Computer programming',
    '2008%E2%80%932014 Spanish financial crisis',
    'World egg',
    'Roman Empire (TV series)',
    'Solar power in Armenia',
    'Lunokhod programme',
    'Rover (space exploration)',
    'Weighted median',
    'History of programming languages',
    'Residual sum of squares',
    'Apple Corps v Apple Computer',
    'Archive 1',
    'Book:Justin Timberlake',
    'Terence Young (director)',
    'Hollywood Hills',
    'Root-mean-square deviation',
    'Epigenetic therapy',
    'Article Two of the United States Constitution',
    'Nutriepigenomics',
    'Double agent',
    'Set (deity)',
    'Four sons of Horus',
    'Polish volunteers in the Spanish Civil War',
    'Roman conquest of Britain',
    'DNA-PKcs',
    'Religion in ancient Rome',
    'Hollywood (disambiguation)',
    'Category:Books about Steve Jobs',
    'Epigenetics in insects',
    'Category:Songs written by Justin Timberlake',
    'Category:Redirect-Class The X-Files articles',
    'Six of Crows',
    'Apple%27s transition to Intel processors',
    'Everyone%27s Gone to the Moon',
    'Roman people',
    'Mesoamerican ballgame',
    'Sodomy',
    'Harmonic mean',
    'S%C3%A2rbi Susani church',
    'Category:Films set in Tuscany',
    'Maya Angelou',
    's:Constitution of the United States of America',
    'Maya society',
    'First Amendment to the United States Constitution',
    'Method (computer programming)',
    'Viking program',
    'COBOL',
    'Apple (disambiguation)',
    'Elizabeth Wagmeister',
    'Sixteenth Amendment to the United States Constitution',
    'Baring crisis',
    'Claudine Auger',
    'Microsoft To Do',
    'Justin Timberlake: Live from London',
    'Z-test',
    'Maya Hawke',
    'Template:Steve Jobs',
    'DNA replication',
    'Financial crisis of 2007%E2%80%9308',
    'List of Nobel laureates affiliated with the University of Pennsylvania',
    'Epigenetic effects of smoking',
    'Osiris myth',
    'Carole Crist',
    'Dave Seaman',
    'Triple',
    'Trade in Maya civilization',
    'Peter Lance',
    'Typography of Apple Inc.',
    'Nucleobase',
    'Category:Companies based in Tuscany',
    'The Tubes',
    'Mehit',
    'Solar power tower',
    'Entomopter',
    'Justified (album)',
    'Ancient DNA',
    'Nena die Band (album)',
    'The Unicorn (song)',
    'East German balloon escape',
    'Precision engineering',
    'Dax Jordan',
    'Category:Universities in Tuscany',
    'Bevy Smith',
    'Wikibooks:Computer Programming Principles',
    'List of Nobel Laureates affiliated with the University of Rochester',
    'Mageina Tovah',
    'Data dredging',
    'Roman Italy',
    'Solar cell efficiency',
    'Fourth Amendment to the United States Constitution',
    'Lunar distance (astronomy)',
    'Chichen Itza',
    'Category:Palaces in Tuscany',
    'Category:Computer programmers',
    'F-test of equality of variances',
    'Siege of Madrid',
    'Duat',
    'Hollywood (Bukowski novel)',
    'Circular error probable',
    'Hollywood Hotel',
    'St. Martin%27s Day',
    'John Sculley',
    'Deep Six',
    '2010 March 3',
    'Matilda of Tuscany',
    'Least-squares spectral analysis',
    'Epigenetics of cocaine addiction',
    'Kahan summation algorithm',
    'Richard Johnson (columnist)',
    'Epigenetics of diabetes Type 2',
    'Hollywood Boulevard',
    'List of Xbox Game Studios video games',
    'Constitutional Convention (United States)',
    'Template:Non-free manual reduce',
    'Category:Rivers of Tuscany',
    'Baucis and Philemon',
    'DNA digital data storage',
    'Special Team Six',
    'Madame X Tour',
    'Maya mythology',
    'Irish Brigade (Spanish Civil War)',
    'List of Nobel laureates in Physiology or Medicine',
    'Maya civilization',
    'List of artificial objects on Mars',
    'Polynomial least squares',
    'Carlo Karges',
    'San Gimignano',
    'Dagger (typography)',
    'List of economic crises',
    'Category:Computer programming books',
    'Kevin McAlea',
    'Atum',
    'Microsoft account',
    'Epigenetics and melanoma',
    'One page view - full manual',
    'Timeline of programming languages',
    'The Triple Cross',
    'Ch (computer programming)',
    'David Slade',
    'Solar power in Morocco',
    'Economy of the Maya civilization',
    'Talk%3AStatistical significance',
    'Cinema of the United States',
    'b:Computer Programming',
    'Nobel Prize in Physics',
    'Maya Sharma',
    'Objective precision',
    'Mean absolute percentage error',
    'Least absolute deviations',
    'Currency crisis',
    'Omnibus test',
    '1938%E2%80%9339 in the Spanish Civil War',
    'Confusion matrix',
    'Call Me Madam',
    'Accuracy and precision',
    'Polynomial regression',
    'HSV epigenetics',
    'Microsoft Outlook',
    'Hamsa',
    'Fair value accounting and the subprime mortgage crisis',
    'Milicianas in the Spanish Civil War',
    'Spanish Maquis',
    'Studio system',
    'Russian financial crisis',
    'Star Trek Star Fleet Technical Manual',
    'Ancient Egyptian creation myths',
    'Pre-Code Hollywood',
    'Page 6',
    'List of Christian Nobel laureates',
    'Solar power in Spain',
    'Category:Manual therapy',
    'Ancient Maya art',
    'Template:US Constitution',
    'Joseph Smith Hypocephalus',
    'Adam Steltzner',
    'Financial contagion',
    'Mother Goose and Grimm',
    'List of Mars landers',
    'Computer science',
    'Francisco Franco',
    'Fixed-point arithmetic',
    'Category:United States Constitution',
    'Microsoft Windows',
    'Compound steam engine',
    'Mayan',
    'Western Roman Empire',
    'European debt crisis',
    'DNA microarray',
    'Apple Bandai Pippin',
    'SolarCity',
    'Non-negative least squares',
    'Steve Jobs: The Lost Interview',
    'List of programming languages',
    'German involvement in the Spanish Civil War',
    'List of songs recorded by Justin Timberlake',
    'Great Recession in Russia',
    'List of Russian Nobel laureates',
    '1997 Asian financial crisis',
    'Apple Newton',
    'Cancer epigenetics',
    '20 Experience',
    'Category:Steve Jobs',
    'Dmitri Borgmann',
    'Three Crosses Square',
    'Wicked (musical)',
    'Apple Lisa',
    'Solar power in Poland',
    'Talk%3AEye of Horus',
    'Ashitey Trebi-Ollennu',
    'The Manual',
    'Circle of antisimilitude',
    'Maya music',
    'Precision: The Measure of All Things',
    'List of Muslim Nobel laureates',
    'Least squares',
    'The History of the Decline and Fall of the Roman Empire',
    'Christian cross variants',
    'Roman Republic',
    'Say Something (Justin Timberlake song)',
    '2008%E2%80%932011 Icelandic financial crisis',
    'Mike Markkula',
    'A-DNA',
    'Book:Steve Jobs',
    'Human sacrifice in Maya culture',
    'Autodesk Maya',
    'List of Nobel laureates affiliated with Harvard University',
    'Solar power in China'
}
